### ISSUE TITLE
Assigner Assertion Failure

### ISSUE THREAD

**Issue by 0xAleksaOpacic** [NilFoundation/zkllvm-rust-template#2]
## Description
When attempting to use the assigner command with specific inputs, an assertion failure occurs, indicating a size mismatch between `stack_memory[dst].size and stack_memory[src].size.` This issue leads to an aborted process with a core dump.

## Commit Hash
afd38089bf68d9dac36f0a76149b02308a72750b

## How to Reproduce

Just follow readme instructions and it fails at:
`assigner -b target/assigner-unknown-unknown/release/zkllvm-rust-template.ll -i inputs/example.inp -t assignment.tbl -c circuit.crct -e pallas`

**Comment by rsoury** [comment]
+1

-- 

**Note:** This seems associated to the use of Fields within the example?

**Comment by aleasims** [comment]
Fixed in this PR:

- #3 

The actual issue is that we do not specify compatible versions here. If you had fallen back to `zkLLVM 0.1.14`, it would have worked fine.

Current version is compatible with `zkLLVM 0.1.18`.

Closing as solved.
